### ISSUE TITLE
Unhandled exception thrown by application when using a specific image with extreme height

### ISSUE THREAD

**Issue by NathanPortelli** [SixLabors/ImageSharp.Web#172]
### Prerequisites

- [x] I have written a descriptive issue title
- [x] I have verified that I am running the latest version of ImageSharp
- [x] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When inserting the attached image, it refuses to show and produces the following fail in VS Debug Console; 

```
Microsoft.AspNetCore.Server.Kestrel[13]
      Connection id "0HM9FH4P35QNA", Request id "0HM9FH4P35QNA:00000003": An unhandled exception was thrown by the application.
      SixLabors.ImageSharp.UnknownImageFormatException: Image cannot be loaded. Available decoders:
       - JPEG : JpegDecoder
       - PNG : PngDecoder
       - BMP : BmpDecoder
       - TGA : TgaDecoder
       - GIF : GifDecoder
      
         at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Stream stream, IImageFormat& format)
         at SixLabors.ImageSharp.Web.FormattedImage.Load(Configuration configuration, Stream source)
         at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.<>c__DisplayClass18_0.<<ProcessRequestAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.<>c__DisplayClass18_0.<<ProcessRequestAsync>b__0>d.MoveNext()
      --- End of stack trace from previous location ---
         at SixLabors.ImageSharp.Web.Middleware.ConcurrentDictionaryExtensions.GetOrAddAsync[TKey,TValue](ConcurrentDictionary`2 dictionary, TKey key, Func`2 valueFactory)
         at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.ProcessRequestAsync(HttpContext context, IImageResolver sourceImageResolver, ImageContext imageContext, IDictionary`2 commands)
         at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Steps to Reproduce
![b5035dcb-22ee-4098-8ccc-b1d53a4fec52_download](https://user-images.githubusercontent.com/61872215/121971867-0e075d80-cd7a-11eb-8e7d-9f1edb3ff9f9.jpeg)
Attempt to use the attached image with, in my case, "?height=600&width=600&rmode=max", although other dimensions also have the same issue.

### System Configuration

- ImageSharp.Web version: 1.0.3
- Other ImageSharp.Web packages and versions: 
- Environment (Operating system, version and so on): Windows 10 Pro - 10.0.19041 Build 19041
- .NET Framework version: ASP.NET Core 5.0
- Additional information:

**Comment by JimBobSquarePants** [comment]
The exception thrown is an `UnknownImageFormatException` which means that ImageSharp is unable to identify the image format. The image you have linked is definitely a jpeg but that could be GitHub rewriting it. Could you please attach the original in a zip file?

Also, what `IImageProvider` implementation are you using?

**Comment by NathanPortelli** [comment]
The original image is in .jpeg format, attached please find the same image in .zip folder.
[image.zip](https://github.com/SixLabors/ImageSharp.Web/files/6658255/image.zip)

I do not have an Image Provider set up, but I have the following in ````startup.cs```;

**ConfigureServices**
```
services.AddImageSharp()
                .RemoveProcessor<FormatWebProcessor>()
                .RemoveProcessor<BackgroundColorWebProcessor>();
```

**Configure**
```
app.UseImageSharp();
```

**Comment by JimBobSquarePants** [comment]
I'm afraid I am unable to replicate this issue with the provided image.

![image](https://user-images.githubusercontent.com/385879/122631775-0b806d00-d0c6-11eb-9ec8-46b92019e46c.png)

Here's the default ASP.NET Core MVC I used to generate the image. There are no modifications other than to register ImageSharp.Web in an identical manner as to which you provided.

[issue172.zip](https://github.com/SixLabors/ImageSharp.Web/files/6680053/issue172.zip)
