### ISSUE TITLE
SixLabors.ImageSharp.ImageFormatException: Bad method for ZLIB header: cmf=80 when loading png image

### ISSUE THREAD

**Issue by deMD** [SixLabors/ImageSharp.Web#198]
### Prerequisites

- [x] I have written a descriptive issue title
- [ ] I have verified that I am running the latest version of ImageSharp
- [ ] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [x] I have searched [open](https://github.com/SixLabors/ImageSharp/issues) and [closed](https://github.com/SixLabors/ImageSharp/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description

When using Umbraco 9 on Azure Web Apps using Azure Storage to save media I get the following exception in ImageSharp:
```
SixLabors.ImageSharp.ImageFormatException: Bad method for ZLIB header: cmf=80

   at SixLabors.ImageSharp.Formats.Png.Zlib.ZlibInflateStream.InitializeInflateStream(Boolean isCriticalChunk)

   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.ReadScanlines[TPixel](PngChunk chunk, ImageFrame`1 image, PngMetadata pngMetadata)

   at SixLabors.ImageSharp.Formats.Png.PngDecoderCore.Decode[TPixel](BufferedReadStream stream, CancellationToken cancellationToken)

   at SixLabors.ImageSharp.Formats.ImageDecoderUtilities.Decode[TPixel](IImageDecoderInternals decoder, Configuration configuration, Stream stream, Func`3 largeImageExceptionFactory)

   at SixLabors.ImageSharp.Formats.Png.PngDecoder.Decode[TPixel](Configuration configuration, Stream stream)

   at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)

   at SixLabors.ImageSharp.Image.<>c__DisplayClass133_0`1.<Load>b__0(Stream s)

   at SixLabors.ImageSharp.Image.WithSeekableStream[T](Configuration configuration, Stream stream, Func`2 action)

   at SixLabors.ImageSharp.Image.Load[TPixel](Configuration configuration, Stream stream, IImageFormat& format)

   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.<>c__DisplayClass18_0.<<ProcessRequestAsync>b__0>d.MoveNext()

--- End of stack trace from previous location ---

   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.<>c__DisplayClass18_0.<<ProcessRequestAsync>b__0>d.MoveNext()

--- End of stack trace from previous location ---

   at SixLabors.ImageSharp.Web.Middleware.ConcurrentDictionaryExtensions.GetOrAddAsync[TKey,TValue](ConcurrentDictionary`2 dictionary, TKey key, Func`2 valueFactory)

   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.ProcessRequestAsync(HttpContext context, IImageResolver sourceImageResolver, ImageContext imageContext, IDictionary`2 commands)

   at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext context)

   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)

   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 121

   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()

--- End of stack trace from previous location ---

   at Umbraco.Cms.Web.Common.Middleware.PreviewAuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()

--- End of stack trace from previous location ---

   at Umbraco.Cms.Web.Common.Middleware.UmbracoRequestLoggingMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)

   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Server.IIS.Core.IISHttpContextOfT`1.ProcessRequestAsync()
   ```
   
This issue seems to only be caused when using Azure/Azure storage. When running on localhost with Azure Storage emulator as media storage the image does load without problems.

### Steps to Reproduce
Not available as I don't know exactly in what circumstances the issues occur. I do know this images doesn't show up when using query parameters on our development environment running in the configuration mentioned below: https://www.wearetriple.com/media/qfsl0o2c/vodafone-header-image-triple.png

### System Configuration
Azure Web App S1 tier
Standard LRS Tier Azure Storage
.Net 6

- ImageSharp version: 1.0.4
- Other ImageSharp packages and versions: SixLabors.ImageSharp.Web.Providers.Azure 1.0.3
- Environment (Operating system, version and so on): Azure Web App running Windows
- .NET Framework version: .Net 6
- Additional information: I use Umbraco 9 as cms.

**Comment by deMD** [comment]
Hi,

Upgrading to the lastest versions of ImageSharp, ImageSharp.Web and ImageSharp.Web.Providers.Azure sadly did not work for me. However, when I downgraded the project from .Net 6 back to .Net 5 images started to render properly. So seems something somewhere, either in one of the ImageSharp libraries, or in Umbraco packages, causes issues with rendering in .Net 6

**Comment by JimBobSquarePants** [comment]
That’s interesting. I’ll retest specifically targeting .NET 6

**Comment by JimBobSquarePants** [comment]
I just tested again using the sample app in ImageSharp.Web targeting .NET 6 to pull the image from Azure Blob Storage. I'm still unable to replicate the issue. 

I suggest using the same sample application to query the image from your development environment location to confirm.

**Comment by JimBobSquarePants** [comment]
The library targets those frameworks (same as the current release) but you can easily change the target framework in the sample application to target `net6.0`.

**Comment by deMD** [comment]
Been doing some tests and also couldn't replicate it. In the end decided to re-upgrade my project to .Net 6 and it also seems to work there now. I have the feeling maybe some implicit referenced NuGet packages caused to issue or something. Nevertheless the issue seems to have vanished for me so I'll close this issue for now.

**Comment by JimBobSquarePants** [comment]
>I have the feeling maybe some implicit referenced NuGet packages caused to issue or something. 

I think your assessment is likely correct. We had issues with .NET 6 due to a change in stream reading. v1.0.4 was released with a fix. I think the reference to SixLabors.ImageSharp.Web.Providers.Azure 1.0.3 was somehow pulling in the upstream 1.0.3 version.
