### ISSUE TITLE
DirectoryNotFoundException: ... \wwwroot\ for Azure blob storage provider

### ISSUE THREAD

**Issue by vpetrusevici** [SixLabors/ImageSharp.Web#255]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp.Web
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp.Web version

2.0

### Other Six Labors packages and versions

2.0.0-alpha.0.27

### Environment (Operating system, version and so on)

Windows

### .NET Framework version

.NET 6

### Description

After update to 2.0 stable or 2.0.0-alpha.0.27+ I can't run application without wwwroot directory (I don't have any static files and use Azure Blob Sorage for images).
It works well with version 2.0.0-alpha.0.26

### Steps to Reproduce

My program.cs:
``
var imageSharpServices = services.AddImageSharp(options =>
{
    options.CacheMaxAge = TimeSpan.FromDays(7);
})
        .RemoveProcessor<FormatWebProcessor>()
        .RemoveProcessor<BackgroundColorWebProcessor>()
        .RemoveProcessor<QualityWebProcessor>();
    services.Configure<AzureBlobStorageImageProviderOptions>(options =>
    {
        options.BlobContainers.Add(new AzureBlobContainerClientOptions
        {
            ConnectionString = azureStorageSettings["ConnectionString"],
            ContainerName = azureStorageSettings["ContainerName"]
        });
    });
    services.Configure<AzureBlobStorageCacheOptions>(options =>
    {
        options.ConnectionString = azureStorageSettings["ConnectionString"];
        options.ContainerName = azureStorageSettings["CacheContainerName"];
        AzureBlobStorageCache.CreateIfNotExists(options, PublicAccessType.None);
    });
    imageSharpServices
        .RemoveProvider<PhysicalFileSystemProvider>()
        .AddProvider<AzureBlobStorageImageProvider>()
        .SetCache<AzureBlobStorageCache>();``
Stack trace:
``System.IO.DirectoryNotFoundException: C:\AzureAgent\_work\1\s\API\FastArticle\wwwroot\
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
           at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
           at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
           at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType)
           at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
           at Microsoft.Extensions.Internal.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
           at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_0.<UseMiddleware>b__0(RequestDelegate next)
           at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
           at Microsoft.AspNetCore.Builder.WebApplicationBuilder.<ConfigureApplication>b__27_0(RequestDelegate next)
           at Microsoft.AspNetCore.Builder.ApplicationBuilder.Build()
           at Microsoft.AspNetCore.Hosting.GenericWebHostService.StartAsync(CancellationToken cancellationToken)
  Unhandled exception. System.AggregateException: One or more errors occurred. (C:\AzureAgent\_work\1\s\API\FastArticle\wwwroot\)
   ---> System.IO.DirectoryNotFoundException: C:\AzureAgent\_work\1\s\API\FastArticle\wwwroot\
     at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root, ExclusionFilters filters)
     at Microsoft.Extensions.FileProviders.PhysicalFileProvider..ctor(String root)
     at SixLabors.ImageSharp.Web.Providers.PhysicalFileSystemProvider.GetProvider(IOptions`1 options, IWebHostEnvironment environment)
     at SixLabors.ImageSharp.Web.Providers.PhysicalFileSystemProvider..ctor(IOptions`1 options, IWebHostEnvironment environment, FormatUtilities formatUtilities)
     at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
     at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
     at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
``

**Comment by JimBobSquarePants** [comment]
Your service registration is all over the place.  Can you please try again using only the builder to register and configure services

**Comment by JimBobSquarePants** [comment]
I can't replicate this in my local environment. All services are correctly registered and the constructor for `PhysicalFileSystemProvider` is never called.

**Comment by vpetrusevici** [comment]
@JimBobSquarePants  sorry, looks like it was my problem with configs. Thank you for reply! I'll close it. Sorry again for wasting your time

**Comment by JimBobSquarePants** [comment]
@vpetrusevici That's a sigh of relief! No worries and thanks for taking the time to fill in all the detail when posting.
