### ISSUE TITLE
Azure middleware trows an exception in 3.0+ version

### ISSUE THREAD

**Issue by vpetrusevici** [SixLabors/ImageSharp.Web#318]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have verified that I am running the latest version of ImageSharp.Web
- [X] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [X] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### ImageSharp.Web version

3.0.1-alpha.0.7

### Other Six Labors packages and versions

SixLabors.ImageSharp.Web.Providers.Azure 3.0.0-alpha.0.13

### Environment (Operating system, version and so on)

linux in doker

### .NET Framework version

7

### Description

Hi! I have strange new exception for Azure web providers when i'm triing to get image in webp format (it was saved in this format).
```2023-03-26T14:09:11.709607171Z       SixLabors.ImageSharp.UnknownImageFormatException: Image cannot be loaded. Available decoders:
2023-03-26T14:09:11.709611071Z        - PNG : PngDecoder
2023-03-26T14:09:11.709615071Z        - GIF : GifDecoder
2023-03-26T14:09:11.709618571Z        - TGA : TgaDecoder
2023-03-26T14:09:11.709632771Z        - PBM : PbmDecoder
2023-03-26T14:09:11.709636371Z        - BMP : BmpDecoder
2023-03-26T14:09:11.709639971Z        - Webp : WebpDecoder
2023-03-26T14:09:11.709643471Z        - JPEG : JpegDecoder
2023-03-26T14:09:11.709646971Z        - TIFF : TiffDecoder
2023-03-26T14:09:11.709667572Z
2023-03-26T14:09:11.709671272Z          at SixLabors.ImageSharp.Formats.ImageFormatManager.ThrowInvalidDecoder(ImageFormatManager manager)
2023-03-26T14:09:11.709675172Z          at SixLabors.ImageSharp.Formats.ImageFormatManager.GetEncoder(IImageFormat format)
2023-03-26T14:09:11.709678972Z          at SixLabors.ImageSharp.Web.FormattedImage..ctor(Image image, IImageFormat format, Boolean keepOpen)
2023-03-26T14:09:11.709682672Z          at SixLabors.ImageSharp.Web.FormattedImage.LoadAsync(DecoderOptions options, Stream source)
2023-03-26T14:09:11.709686572Z          at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.ProcessRequestAsync(HttpContext httpContext, IImageResolver sourceImageResolver, ImageContext imageContext, CommandCollection commands, Boolean retry)
2023-03-26T14:09:11.709690572Z          at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.ProcessRequestAsync(HttpContext httpContext, IImageResolver sourceImageResolver, ImageContext imageContext, CommandCollection commands, Boolean retry)
2023-03-26T14:09:11.709694672Z          at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean 
```
For previous versions it worked. Also it's still working for PhysicalFileSystemProvider.

### Steps to Reproduce

Here is my registration code:
```

        var imageSharpServices = services.AddImageSharp()
                .RemoveProcessor<FormatWebProcessor>()
                .RemoveProcessor<BackgroundColorWebProcessor>()
                .RemoveProcessor<QualityWebProcessor>();

        if (isProduction)
        {
            services.AddApplicationInsightsTelemetry();

            services.Configure<AzureBlobStorageImageProviderOptions>(options =>
            {
                options.BlobContainers.Add(new AzureBlobContainerClientOptions
                {
                    ConnectionString = azureStorageSettings["ConnectionString"],
                    ContainerName = azureStorageSettings["ContainerName"]
                });
            });
            services.Configure<AzureBlobStorageCacheOptions>(options =>
            {
                options.ConnectionString = azureStorageSettings["ConnectionString"];
                options.ContainerName = azureStorageSettings["CacheContainerName"];
                AzureBlobStorageCache.CreateIfNotExists(options, PublicAccessType.None);
            });
            imageSharpServices
                .RemoveProvider<PhysicalFileSystemProvider>()
                .AddProvider<AzureBlobStorageImageProvider>()
                .SetCache<AzureBlobStorageCache>();
        }
```

Example request "https://{domain}/images-container/cb436d6f-e6ee-4339-af62-872bc5241c68.webp?width=500&height=325&rmode=max"

**Comment by JimBobSquarePants** [comment]
You sure the image at the endpoint is ok? 

Are you able to provide it?

**Comment by vpetrusevici** [comment]
yep. just downloaded it directly from container 
[a9720106-1911-4a3f-9abc-b935d27fe6fb.zip](https://github.com/SixLabors/ImageSharp.Web/files/11071972/a9720106-1911-4a3f-9abc-b935d27fe6fb.zip)

**Comment by vpetrusevici** [comment]
it was also changed by imagesharp before upload. original image: 
![IMG_20201115_142106](https://user-images.githubusercontent.com/40790510/227784217-888d6e09-e9c7-44c6-a6b6-36a1a87d8338.jpg)

**Comment by vpetrusevici** [comment]
[cb436d6f-e6ee-4339-af62-872bc5241c68.zip](https://github.com/SixLabors/ImageSharp.Web/files/11072001/cb436d6f-e6ee-4339-af62-872bc5241c68.zip)
One more image from exception in example

**Comment by vpetrusevici** [comment]
I tried to reproduced local and noticed strange thing. It doesn't use Azure at all, only local file storage. Looks like 
```
.RemoveProvider<PhysicalFileSystemProvider>()
.AddProvider<AzureBlobStorageImageProvider>()
```
doesn't work. But in debug these lines were applied

**Comment by vpetrusevici** [comment]
nope, sorry. it was a cache. It just doesn't work and returns 404 on local

**Comment by vpetrusevici** [comment]
I found the latest working version
    <PackageReference Include="SixLabors.ImageSharp" Version="3.0.0-alpha.0.34" />
    <PackageReference Include="SixLabors.ImageSharp.Web.Providers.Azure" Version="3.0.0-alpha.0.7" />

**Comment by JimBobSquarePants** [comment]
Why are you using 2 different alpha versions of the ImageSharp.Web packages?

**Comment by vpetrusevici** [comment]
sorry, i meant ImageSharp* version
3.0.1-alpha.0.7

**Comment by vpetrusevici** [comment]
So I tried with 
```
<PackageReference Include="SixLabors.ImageSharp" Version="3.0.1-alpha.0.7" />
<PackageReference Include="SixLabors.ImageSharp.Web.Providers.Azure" Version="3.0.0-alpha.0.13" />
```

**Comment by vpetrusevici** [comment]
```
 Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
      SixLabors.ImageSharp.UnknownImageFormatException: Image cannot be loaded. Available decoders:
       - JPEG : JpegDecoder
       - PNG : PngDecoder
       - GIF : GifDecoder
       - BMP : BmpDecoder
       - TIFF : TiffDecoder
       - TGA : TgaDecoder
       - PBM : PbmDecoder
       - Webp : WebpDecoder

         at SixLabors.ImageSharp.Formats.ImageFormatManager.ThrowInvalidDecoder(ImageFormatManager manager)
         at SixLabors.ImageSharp.Formats.ImageFormatManager.GetEncoder(IImageFormat format)
         at SixLabors.ImageSharp.Web.FormattedImage..ctor(Image image, IImageFormat format, Boolean keepOpen)
         at SixLabors.ImageSharp.Web.FormattedImage.LoadAsync(DecoderOptions options, Stream source)
         at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.ProcessRequestAsync(HttpContext httpContext, IImageResolver sourceImageResolver, ImageContext imageContext, CommandCollection commands, Boolean retry)
         at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.ProcessRequestAsync(HttpContext httpContext, IImageResolver sourceImageResolver, ImageContext imageContext, CommandCollection commands, Boolean retry)
         at SixLabors.ImageSharp.Web.Middleware.ImageSharpMiddleware.Invoke(HttpContext httpContext, Boolean retry)
         at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
         at NSwag.AspNetCore.Middlewares.SwaggerUiIndexMiddleware.Invoke(HttpContext context)
         at NSwag.AspNetCore.Middlewares.RedirectToIndexMiddleware.Invoke(HttpContext context)
         at NSwag.AspNetCore.Middlewares.OpenApiDocumentMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.HandleException(HttpContext context, ExceptionDispatchInfo edi)
         at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddlewareImpl.<Invoke>g__Awaited|8_0(ExceptionHandlerMiddlewareImpl middleware, HttpContext context, Task task)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```
```
<PackageReference Include="SixLabors.ImageSharp" Version="3.0.1" />
 <PackageReference Include="SixLabors.ImageSharp.Web.Providers.Azure" Version="3.0.0-alpha.0.13" />
```

**Comment by vpetrusevici** [comment]
The same for 
```
    <PackageReference Include="SixLabors.ImageSharp" Version="3.0.2-alpha.0.6" />
    <PackageReference Include="SixLabors.ImageSharp.Web.Providers.Azure" Version="3.0.0-alpha.0.13" />
```

**Comment by vpetrusevici** [comment]
@hey-red is right! I just removed direct SixLabors.ImageSharp dependency and it's working now.
Thank you guys! And sorry for wasting your time

**Comment by vpetrusevici** [comment]
@JimBobSquarePants 
Can confirm. It works with this version too

**Comment by JimBobSquarePants** [comment]
Awesome. Thanks! I'll be shipping a stable release today.
