### ISSUE TITLE
AddProvider -> implementationFactory throws exception on Startup

### ISSUE THREAD

**Issue by deanmarcussen** [SixLabors/ImageSharp.Web#61]
### Prerequisites

- [ y] I have written a descriptive issue title
- [ y] I have verified that I am running the latest version of ImageSharp.Web
- [ y] I have verified if the problem exist in both `DEBUG` and `RELEASE` mode
- [ y] I have searched [open](https://github.com/SixLabors/ImageSharp.Web/issues) and [closed](https://github.com/SixLabors/ImageSharp.Web/issues?q=is%3Aissue+is%3Aclosed) issues to ensure it has not already been reported

### Description
Using the `AddProvider()` builder extension with an implementation factory throws an exception.

```
System.ArgumentException
  HResult=0x80070057
  Message=Implementation type cannot be 'SixLabors.ImageSharp.Web.Providers.IImageProvider' because it is indistinguishable from other services registered for 'SixLabors.ImageSharp.Web.Providers.IImageProvider'.
Parameter name: descriptor
  Source=Microsoft.Extensions.DependencyInjection.Abstractions
  StackTrace:
   at Microsoft.Extensions.DependencyInjection.Extensions.ServiceCollectionDescriptorExtensions.TryAddEnumerable(IServiceCollection services, ServiceDescriptor descriptor)
   at SixLabors.ImageSharp.Web.DependencyInjection.ImageSharpCoreBuilderExtensions.AddProvider(IImageSharpCoreBuilder builder, Func`2 implementationFactory) in E:\Sites\ImageSharp.Web\src\ImageSharp.Web\DependencyInjection\ImageSharpCoreBuilderExtensions.cs:line 156
   at SixLabors.ImageSharp.Web.Sample.Startup.ConfigureServices(IServiceCollection services) in E:\Sites\ImageSharp.Web\samples\ImageSharp.Web.Sample\Startup.cs:line 22
```

### Steps to Reproduce
Add the following code to the samples project `Startup`
```
                .AddProvider(sp => new PhysicalFileSystemProvider(
                    sp.GetRequiredService<IOptions<ImageSharpMiddlewareOptions>>(),
                    sp.GetRequiredService<IHostingEnvironment>(),
                    sp.GetRequiredService<MemoryAllocator>()))
```

### System Configuration

Clone of `ImageSharp.Web`

**Comment by deanmarcussen** [comment]
Nope, my own fault, I was one commit behind master, and this is fixed :)
